### ISSUE TITLE
Reference to obsolete developers guide

### ISSUE THREAD

**Issue by demarant** [eea/docs#1]
in the section https://github.com/eea/docs/blob/gh-pages/Development-guidelines/index.md#development-guidelines
we have a reference to an obsolete not maintained page 
https://github.com/eea/docs/blob/gh-pages/Development-guidelines/index.md#development-guidelines

I suggest we bring that page into this docs repo an update it (easier when we have it in this common repo) before linking to it.

**Comment by demarant** [comment]
I added a system message to the user on the page http://www.eionet.europa.eu/software/swstandards
saying that the page is obsolete. At least it is clear now. I hope somebody takes responsibility and takes down / archive pages that are not maintained.

**Comment by sorenroug** [comment]
We're removing the docs repo now.
